#!/bin/bash
# DEFINE EXIT CODES
SUCCESSFUL=0
INTERPRETER_NOT_FOUND=1
TIMEOUT=2

#Set up args
HOST=$1
PORT=$2
SID=$3
USER=$4
PASSWORD=$5
PKG_DIR=$6
SQL_CODE_FILE=$7
SQL_INTERPRETER=$8
ATOM_NLS_LANG=$9

#Set up constants
LIB_DIR=${PKG_DIR}/lib
COMPILE_SCRIPT_SIMPLE=${LIB_DIR}/compileSimple.sql

#Set the NLS_LANG from settings if its not set.
if [[ -z ${NLS_LANG+x} ]]; then
    export NLS_LANG=${ATOM_NLS_LANG}
fi

${SQL_INTERPRETER} ${USER}/${PASSWORD}@//${HOST}:${PORT}/${SID} @${COMPILE_SCRIPT_SIMPLE} \"${SQL_CODE_FILE}\"
exit ${SUCCESSFUL}
